AWSTemplateFormatVersion: "2010-09-09"

Description: "This is a template to create an ApiGateway with VPC Link that connects to an internal NLB with specific outbound target ports"

Parameters:
  # Assuming VPC already exists, provide VPC ID
  ExistingVpcId:
    Type: String
    Description: "ID of the existing VPC"

  # Assuming Subnets already exist, provide Subnet IDs
  ExistingSubnetId1:
    Type: String
    Description: "ID of the existing public subnet 1"

  ExistingSubnetId2:
    Type: String
    Description: "ID of the existing public subnet 2"

Resources:
  # Security Group Definition
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow inbound and outbound traffic for NLB"
      VpcId: !Ref ExistingVpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 44311
          ToPort: 44313
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: CreatedBy
          Value: MaureenO.

  # Internal Network Load Balancer Definition
  MyNLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref ExistingSubnetId1
        - !Ref ExistingSubnetId2
      SecurityGroups:
        - !Ref MySecurityGroup
      Scheme: internal
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"
      Tags:
        - Key: CreatedBy
          Value: MaureenO.
  
  # API Gateway Definition
  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiGateway
      FailOnWarnings: "true"
      Tags:
        - Key: CreatedBy
          Value: MaureenO.

  # VPC Link Definition
  MyVpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: MyVpcLink
      TargetArns:
        - !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:loadbalancer/net/${MyNLB}
      Tags:
        - Key: CreatedBy
          Value: MaureenO.

Outputs:
  # Output the ID of the created API Gateway
  ApiGatewayId:
    Value: !Ref MyApiGateway
    Description: "ID of the created API Gateway"

  # Output the ID of the created VPC Link
  VpcLinkId:
    Value: !Ref MyVpcLink
    Description: "ID of the created VPC Link"

  # Output the DNS name of the Internal Network Load Balancer
  LoadBalancerDnsName:
    Value: !GetAtt MyNLB.DNSName
    Description: "DNS name of the Internal Network Load Balancer"
